process-engine/management_api_contracts

.gitignore, .npmignore, ISSUE_TEMPLATE.md, Jenkinsfile, PULL_REQUEST_TEMPLATE.md, README.md, gulpfile.js, package.json, src/imanagement_api_accessor.ts, src/imanagement_api_service.ts, src/index.ts, src/management_context.ts, src/management_request.ts, src/process_model_execution/index.ts, src/process_model_execution/process_start_request_payload.ts, src/process_model_execution/process_start_response_payload.ts, src/process_model_execution/start_callback_type.ts, src/rest_settings.ts, tsconfig.json, tslint.json
This PR marks the first feature in the ManagementAPI.
It is a duplicate behavior of the one implemented in the ConsumerAPI counterpart.
A main difference is the use of namespaces to dissect functional parts of the API from each other.
This PR is also meant to be the first example of how to use namespaces for such a scenario.
Currently there is no integration test setup for the ManagementAPI.
This will follow after a manual integrative test.
=> Add "StartProcess" to process model execution namespace

src/data_models/event.ts, src/data_models/event_list.ts, src/data_models/index.ts, src/imanagement_api_service.ts, src/index.ts, src/process_model_execution/process_start_request_payload.ts, src/rest_settings.ts
* added a method for getting events for a process model
* added `Event` and `EventList` models
=> Get events for process model

src/data_models/process_model_execution/index.ts, src/data_models/process_model_execution/update_process_definitions_request_payload.ts, src/imanagement_api_service.ts, src/index.ts, src/rest_settings.ts
* renamed all variations of `UpdateProcessModel` to `UpdateProcessDefinitions` to reflect the change of entity
* added query params to `restSettings`
All integration tests in meta repositories should run successfully: 
* https://github.com/process-engine/management_api_meta/pull/6
* https://github.com/process-engine/consumer_api_meta/pull/40
* https://github.com/process-engine/deployment_api_meta/pull/3
* https://github.com/process-engine/process_engine_meta/pull/122
=> Process definitions instead of process model

package.json
This PR updates the consumer_api_contracts dependency
- Run
```bash
npm install
npm list @process-engine/consumer_api_contracts
```
- The output should contain
```
@process-engine/consumer_api_contracts@0.15.0
```
=> ⬆️ Update Dependency

PULL_REQUEST_TEMPLATE.md, package.json, src/imanagement_api_accessor.ts, src/imanagement_api_service.ts, src/management_context.ts, src/management_request.ts, src/rest_settings.ts
**Changes:**
Add all necessary contracts for the heatmap feature
Implement the contracts.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>
Please …
=> ✨Add Contracts for Heatmap Update

package.json, src/imanagement_api_service.ts, src/rest_settings.ts
**Changes:**
1. Change all dependencies to fixed versions
2. Add interface method and route for the `getProcessModelForCorrelation` function
**Issues:**
Closes #18
PR: #19
Implement the contracts.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> ✨ Get process model for correlation

package.json, src/data_models/index.ts, src/data_models/messages/bpmn_events/base_bpmn_event_message.ts, src/data_models/messages/bpmn_events/end_event_reached.ts, src/data_models/messages/bpmn_events/index.ts, src/data_models/messages/bpmn_events/message_event_reached.ts, src/data_models/messages/bpmn_events/signal_event_reached.ts, src/data_models/messages/bpmn_events/terminate_end_event_reached.ts, src/data_models/messages/callback_types.ts, src/data_models/messages/event_aggregator_settings.ts, src/data_models/messages/index.ts, src/data_models/messages/system_events/base_system_event_message.ts, src/data_models/messages/system_events/finish_user_task.ts, src/data_models/messages/system_events/index.ts, src/data_models/messages/system_events/process_ended.ts, src/data_models/messages/system_events/process_terminated.ts, src/data_models/messages/system_events/user_task_finished.ts, src/data_models/messages/system_events/user_task_reached.ts, src/imanagement_api.ts, src/index.ts, src/socket_settings.ts
**Changes:**
2. Added `onUserTaskWaiting` to `IManagementApiService` to subscribe to `UserTaskWaitingMessage`.
3. Added `onUserTaskFinished` to `IManagementApiService` to subscribe to `UserTaskFinishedMessage`.
4. Added `onProcessEnded` to `IManagementApiService` to subscribe to `ProcessEndedMessage`.
5. Added `onProcessTerminated` to `IManagementApiService` to subscribe to `ProcessEndedMessage`.
7. Added `socketSettings` to have a singular point for route and namespace declarations used in the `ManagementApiSocketEndpoint`.
**Issues:**
https://github.com/process-engine/process_engine_runtime/issues/71
PR: #20 
---
See https://github.com/process-engine/consumer_api_meta/pull/48.
<details>
<summary>
:warning: Before merging …
=> ✨ Add async notifications

package.json, src/data_models/user_task/user_task.ts
**Changes:**
1. Add `name` to the UserTask type.
2. Upgrade to gulp v4.0.0 to close vulnerabilities.
PR: #25
Use the contracts somewhere.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre>
</details>
<details>
<summary>
Expand for a list …
=> ✨ Add a Name Field to the UserTask type

package.json, src/data_models/messages/event_aggregator_settings.ts, src/data_models/user_task/user_task.ts, src/imanagement_api.ts, src/rest_settings.ts
**Changes:**
1. Add the `FlowNodeInstanceId` to the UserTask datatype.
2. Use Instance IDs for UserTask Http Requests, instead of ModelIds.
3. Use Instance IDs for UserTask Events, instead of ModelIds.
4. Change the parameter names for the `finishUserTask` UseCase to indicate InstanceIds, not ModelIds.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/126
PR: #27
Implement the Contracts and use the defined routes and events to handle UserTasks.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: …
=> ♻️🔒 Use unique ids for UserTask events

src/imanagement_api.ts, src/rest_settings.ts
**Changes:**
1. Add delete process model functionality
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/64
PR: #28
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/141**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> ✨ Add Delete Process Model Functionality

package.json, src/data_models/event/event.ts, src/data_models/event/event_list.ts, src/data_models/event/event_trigger_payload.ts, src/data_models/event/event_type.ts, src/data_models/event/index.ts, src/imanagement_api.ts, src/rest_settings.ts
**Changes:**
1. Add interfaces and types for the Event API.
2. Rename `getEventsForProcessModel` to `getStartEventsForProcessModel`
PR: #30
Use the contracts to implement the Event API.
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
</code>
</pre> …
=> ✨ Implement event api

src/imanagement_api.ts
**Changes:**
1. Add identity to events
**Issues:**
Related to https://github.com/process-engine/process_engine_runtime/issues/142
PR: #31
- **Have a look at https://github.com/process-engine/process_engine_runtime/pull/151**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> 🔒 Add Identity to Events

package.json, src/data_models/index.ts, src/data_models/manual_task/index.ts, src/data_models/manual_task/manual_task.ts, src/data_models/manual_task/manual_task_list.ts, src/data_models/messages/callback_types.ts, src/data_models/messages/event_aggregator_settings.ts, src/data_models/messages/system_events/finish_manual_task.ts, src/data_models/messages/system_events/index.ts, src/data_models/messages/system_events/manual_task_finished.ts, src/data_models/messages/system_events/manual_task_reached.ts, src/imanagement_api.ts, src/index.ts, src/rest_settings.ts, src/socket_settings.ts
**Changes:**
1. Add ManualTask DataModel
2. Add ManualTask callback types
3. Add ManualTask Rest,Socket and EventAggregator Settings
4. Add SystemEvents for ManualTask
5. Add IManagement Interfaces for ManualTask
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/91
PR: #27
---
See the [examples](#example) for inspiration.
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at …
=> ✨Add ManualTask Interfaces

src/imanagement_api.ts, src/rest_settings.ts
**Changes:**
1. Add function to get ActiveToken by Correlation and ProcessModel
2. Add function to get TokenHistory by Correlation and ProcessModel
PR: #32
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1152**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
Closes …
=> ✨ Add Functions For LiveExecutionTracker

package.json, src/data_models/token_history/index.ts, src/data_models/token_history/token_history_group.ts, src/imanagement_api.ts
**Changes:**
1. Add type TokenHistoryGroup as return type for retrieving the TokenHistory for a ProcessModel in a Correlation.
PR: #33
- **Have a look at https://github.com/process-engine/bpmn-studio/pull/1152**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:**
PR: …
=> 💄 Add Type TokenHistoryGroup

src/data_models/messages/internal/index.ts, src/data_models/messages/public/index.ts, src/data_models/process_model_execution/process_start_response_payload.ts, src/imanagement_api.ts, src/rest_settings.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/194
**Changes:**
1. Add getTokensForProcessInstance
2. Add ProcessInstanceId to ProcessStartResponsePayload
3. Fix Imports
PR: #35 
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:** …
=> ✨ Add Get Token by Process Instance Functionality

src/apis/imanual_task_management_api.ts, src/apis/iprocess_model_management_api.ts, src/apis/iuser_task_management_api.ts, src/rest_settings.ts
> Related to process-engine/process_engine_runtime#207
**Changes:**
1. Add getProcessModelByProcessInstanceId
PR: #38
-  **Have a look at https://github.com/process-engine/bpmn-studio/pull/1225**
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- ...
**Issues:** …
=> ✨ Add getProcessModelByProcessInstanceId

src/data_models/correlation/correlation.ts, src/data_models/correlation/correlation_process_model.ts, src/data_models/correlation/correlation_state.ts
**Changes:**
1. Adds an ErrorState to the Correlation Object on the Management API.
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/229
PR: #40
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
=> ✨ Add an Error State

src/data_models/token_history/token_history_entry.ts
**Changes:**
1. Add 'previousFlowNodeInstanceId' to 'TokenHistoryEntry'
PR: #41
=> ✨ Add 'previousFlowNodeInstanceId' to 'TokenHistoryEntry'

package.json, src/apis/iprocess_model_management_api.ts, src/rest_settings.ts
**Changes:**
1. Make the StartEventId Parameter Optional
**Issues:**
Related: https://github.com/process-engine/process_engine_runtime/issues/252
PR: #42
Run the integration tests.
=> ♻️Make the StartEventId Parameter optional

src/apis/icorrelation_management_api.ts, src/apis/iempty_activity_management_api.ts, src/apis/ievent_management_api.ts, src/apis/ikpi_management_api.ts, src/apis/ilogging_management_api.ts, src/apis/imanual_task_management_api.ts, src/apis/iprocess_model_management_api.ts, src/apis/itoken_history_management_api.ts, src/apis/iuser_task_management_api.ts, src/data_models/event/event.ts, src/data_models/logging/log_entry.ts, src/data_models/manual_task/manual_task.ts, src/data_models/manual_task/manual_task_list.ts, src/data_models/process_models/process_start_request_payload.ts, src/data_models/process_models/process_start_response_payload.ts, src/data_models/process_models/update_process_definitions_request_payload.ts, src/data_models/token_history/token_history_entry.ts, src/data_models/token_history/token_history_group.ts, src/data_models/user_task/user_task.ts, src/data_models/user_task/user_task_config.ts, src/data_models/user_task/user_task_enum_value.ts, src/data_models/user_task/user_task_form_field.ts, src/data_models/user_task/user_task_form_field_type.ts, src/data_models/user_task/user_task_result.ts, src/imanagement_socket_io_accessor.ts, src/messages/event_aggregator_settings.ts, src/messages/system_events/finish_empty_activity.ts, src/messages/system_events/finish_manual_task.ts, src/messages/system_events/finish_user_task.ts, src/messages/system_events/user_task_reached.ts
**Changes:**
Change the code documentations to make it more comprehensive.
Most docs were taken from their Consumer API counterpart, to ensure synchronicity.
1. Add `@throws` sections to all API functions
2. `@returns` now only describes the values that the function returns, not the Promise that wraps the function. That is already covered by the `@async` tag.
3. Remove some docs that serve no useful purpose, such as `The Id.` or `The list.`.
4. Unify usages of terms such as `ID` or `FormFields`.
PR: #45
=> 📖 Rewrite the code docs

src/apis/ilogging_management_api.ts, src/data_models/logging/log_entry.ts, src/rest_settings.ts
> Related to https://github.com/process-engine/process_engine_runtime/pull/306
**Changes:**
1. Add Functions to Get Logs by ProcessInstanceId
2. Add ProcessInstanceId to LogEntry
PR: #48
> **Have a look at https://github.com/process-engine/bpmn-studio/pull/1448**
=> ✨ Add Functions to Get Logs by ProcessInstanceId

src/apis/itoken_history_management_api.ts, src/data_models/correlation/correlation.ts, src/data_models/correlation/correlation_process_instance.ts, src/data_models/correlation/index.ts
**Changes:**
1. Rename property `processModels` to `processInstances` on Correlation-Model.
2. Move `identity` property from correlation to processInstance.
3. Rename API function `getTokensForFlowNodeInstance` to `getTokensForFlowNode`.
**Issues:**
Part of https://github.com/process-engine/process_engine_runtime/issues/311
PR: #49
=> ♻️💄 Fix naming inconsistencies

package.json, src/apis/itoken_history_management_api.ts, src/rest_settings.ts
**Changes:**
1. Add getTokensForFlowNodeByProcessInstanceId to ITokenHistoryManagementApi
**Issues:**
Closes #https://github.com/process-engine/bpmn-studio/issues/1464
PR: #47
---
See the [examples](#example) for inspiration.
> Describe how others can test your changes (you can remove this section for typo fixes etc.)
<details>
<summary>
</summary>
<br>
Example 1:
<pre>
<code>
</code>
</pre>
Example 2:
<pre>
<code>
**Changes:**
- …
=> ✨Add getTokensForFlowNodeByProcessInstanceId

package-lock.json, src/apis/icronjob_management_api.ts, src/data_models/cronjob/cronjob_history_entry.ts, src/data_models/cronjob/index.ts, src/rest_settings.ts
Add interface methods, types and REST settings for getting a cronjob history.
Part of https://github.com/process-engine/process_engine_runtime/issues/365
PR: #55
=> ✨Persist cronjob history

package-lock.json, package.json, src/apis/ievent_management_api.ts, src/apis/iflow_node_instance_management_api.ts, src/apis/inotification_management_api.ts, src/apis/iprocess_model_management_api.ts, src/data_models/event/event_type.ts, src/http_controller/icorrelation_http_controller.ts, src/http_controller/icronjob_http_controller.ts, src/http_controller/iempty_activity_http_controller.ts, src/http_controller/ievent_http_controller.ts, src/http_controller/iflow_node_instance_http_controller.ts, src/http_controller/ikpi_http_controller.ts, src/http_controller/ilogging_http_controller.ts, src/http_controller/imanual_task_http_controller.ts, src/http_controller/index.ts, src/http_controller/iprocess_model_http_controller.ts, src/http_controller/itoken_history_http_controller.ts, src/http_controller/iuser_task_http_controller.ts, src/imanagement_api_accessor.ts, src/imanagement_api_client.ts, src/index.ts
1. Move all notifications to `INotificationApi` interface
2. Rename `IManagementApi` to `IManagementApiClient`
3. Create HttpController interfaces for each API controller
PR: #56
=> ♻️ Split components into separate services

src/apis/iprocess_model_management_api.ts, src/data_models/process_models/process_start_request_payload.ts
1. Make Payload Optional for StartProcessInstance
2. Make InputValues Optional for ProcessStartRequestPayload
Related to process-engine/process_engine_runtime#371
PR: #57
=> ♻️ Make Payload Optional for StartProcessInstance

src/apis/icorrelation_management_api.ts, src/apis/icronjob_management_api.ts, src/apis/iempty_activity_management_api.ts, src/apis/ievent_management_api.ts, src/apis/iflow_node_instance_management_api.ts, src/apis/ikpi_management_api.ts, src/apis/ilogging_management_api.ts, src/apis/imanual_task_management_api.ts, src/apis/iprocess_model_management_api.ts, src/apis/itoken_history_management_api.ts, src/apis/iuser_task_management_api.ts
Add `offset` and `limit` to all queries that return a list.
Part of https://github.com/process-engine/process_engine_runtime/issues/379
PR: #59
=> ✨ Add limit and offset to list queries

src/apis/icronjob_management_api.ts, src/apis/inotification_management_api.ts, src/messages/callback_types.ts, src/messages/cronjob_event_message.ts, src/messages/event_aggregator_settings.ts, src/messages/index.ts, src/messages/system_events/cronjob_created.ts, src/messages/system_events/cronjob_executed.ts, src/messages/system_events/cronjob_removed.ts, src/messages/system_events/cronjob_stopped.ts, src/messages/system_events/cronjob_updated.ts, src/messages/system_events/index.ts, src/socket_settings.ts
1. Add events for cronjobs
PR: #58 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
=> ✨Add events for cronjobs

src/apis/icorrelation_management_api.ts, src/apis/icronjob_management_api.ts, src/apis/iflow_node_instance_management_api.ts, src/apis/ikpi_management_api.ts, src/apis/ilogging_management_api.ts, src/apis/itoken_history_management_api.ts, src/data_models/correlation/correlation_list.ts, src/data_models/correlation/index.ts, src/data_models/cronjob/cronjob_history_list.ts, src/data_models/cronjob/cronjob_list.ts, src/data_models/cronjob/index.ts, src/data_models/empty_activity/empty_activity_list.ts, src/data_models/event/event_list.ts, src/data_models/flow_node_instance/flow_node_instance_list.ts, src/data_models/flow_node_instance/index.ts, src/data_models/kpi/active_token_list.ts, src/data_models/kpi/flow_node_runtime_information_list.ts, src/data_models/kpi/index.ts, src/data_models/logging/index.ts, src/data_models/logging/log_entry_list.ts, src/data_models/manual_task/manual_task_list.ts, src/data_models/process_models/process_model_list.ts, src/data_models/token_history/index.ts, src/data_models/token_history/token_history_entry_list.ts, src/data_models/token_history/token_history_group.ts, src/data_models/user_task/user_task_list.ts
1. Add total count
PR: #61 
> Describe how others can test your changes (not required when fixing typos, linter errors and such)
=> ✨ Add total count

package.json, src/http_controller/index.ts, src/http_controller/iswagger_http_controller.ts, src/rest_settings.ts
1. Add Documentation for Swagger
PR: #64
=> 📝 Add Documentation for Swagger

src/data_models/logging/index.ts, src/data_models/logging/log_entry.ts, src/data_models/logging/metric_measurement_point.ts
Syncs the logging types with their counterparts from [the logging api](https://github.com/process-engine/logging_api/pull/2)
Part of https://github.com/process-engine/process_engine_runtime/issues/429
PR: #65
=> ♻️ Merge Logging and Metric APIs

package.json, src/data_models/correlation/process_instance.ts
1. Add optional `terminatedBy` and `finishedAt` columns to Processinstance model
Part of https://github.com/process-engine/process_engine_runtime/issues/478
PR: #66
=> ✨ Add terminatedBy and finishedAt to ProcessInstances
